## DATA 601 - Spring 2023
### Homework Assignment 1
Total points : (30 + 10)<br>
 Please provide your solutions into the cells provided after question cells. You can create new cells as needed. <br>

Please return your notebook (by uploading as a *.ipynb file) via Blackboard. The name of your notebook should be in the following format: YourLastname_HW01.ipynb (e.g. Borle_HW01.ipynb).

Make sure that your code is in a working condition when you restart the kernel. Notebooks are great tools for exploration but we should be very careful as we write code.

<b>Intro:</b> For this homework, you will install a module called "names". Please visit [https://pypi.org/project/names/](https://pypi.org/project/names/) to learn how to use this module to create random names. To install and import this "names" module, we do the following

In [1]:
# PIP installation

!pip install names

Collecting names
  Downloading names-0.3.0.tar.gz (789 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.1/789.1 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: names
  Building wheel for names (setup.py) ... done
  Created wheel for names: filename=names-0.3.0-py3-none-any.whl size=803682 sha256=48ec1f79f134db154f4d4eb54f5aff8f62997a8828aba3dca38ff3e812a5501b
  Stored in directory: /root/.cache/pip/wheels/fc/9a/6f/78f4282bbcaa2d8c678b73c54c0bb1b7a04009f0d7cec79fce
Successfully built names
Installing collected packages: names
Successfully installed names-0.3.0

Q1. [<span style="color: red;">10 points</span>] After a successful installation, import the module first, then use the "get_first_name" function in the "names" module and create a list of 10 first-names. Name of this list should be "fname". Similarly, use  the "get_last_name" function from the same module and create a list of 10 last-names (list name should be "lname").
- (i) Print your list and make sure that you indeed have 10 names in your lists.
- (ii) Remove the last "first-name" from your "fname" list.
- (iii) Insert a new last-name between the second-last and last items in the "lname" list.
- (iv) Add a first-name to the end of "fname" and remove the first item in the same list.
- (v)  Generate three random first names, print them, and then add three first names at the end of your "fname" list using the "append" command.

In [2]:
#Importing 'names' module.
import names

(i). Print your list and make sure that you indeed have 10 names in your lists.

In [3]:
#We first create empty list.
fname = []
#We use 'for' loop to repeat the process for 'n' number of times.
#range(10) = [0,1,2,....,9]
for i in range(10):
    #we get random names using get_first_name function from name module.
    first_names = names.get_first_name()
    #We append all elements together.
    fname.append(first_names)
#We are using 'f-string' to embed expressions inside a string.
print(f" List of first 10 First names: {fname}")

#Similarly we do this for the last name. Here we change the function to get_last_name.
lname = []
for j in range(10):
    last_names = names.get_last_name()
    lname.append(last_names)
print(f" List of first 10 Last names: {lname}")

 List of first 10 First names: ['Nellie', 'Troy', 'Sandra', 'Billie', 'Ann', 'Susan', 'Jack', 'Janet', 'Maude', 'Jenifer']
 List of first 10 Last names: ['Miller', 'Davis', 'Kelley', 'Wade', 'Mcguire', 'Hawkins', 'Musick', 'Hong', 'Potter', 'Overstreet']

(ii). Remove the last "first-name" from your "fname" list.

In [4]:
#Pop function removes the last item by default, if index is not passed.
fname.pop()
print(f" First names: {fname}")
#print(len(fname))

 First names: ['Nellie', 'Troy', 'Sandra', 'Billie', 'Ann', 'Susan', 'Jack', 'Janet', 'Maude']

(iii). Insert a new last-name between the second-last and last items in the "lname" list.

In [5]:
#insert function is used to add any element in any particular position.
lname.insert(9,names.get_last_name())
print(lname)

['Miller', 'Davis', 'Kelley', 'Wade', 'Mcguire', 'Hawkins', 'Musick', 'Hong', 'Potter', 'Beasley', 'Overstreet']

(iv). Add a first-name to the end of "fname" and remove the first item in the same list.

In [6]:
#Adding first_name at the end of fname
fname.insert(10,names.get_first_name())
print(fname)

#Here we are giving index in pop to remove first name.
fname.pop(0)
print(fname)

['Nellie', 'Troy', 'Sandra', 'Billie', 'Ann', 'Susan', 'Jack', 'Janet', 'Maude', 'Brandon']
['Troy', 'Sandra', 'Billie', 'Ann', 'Susan', 'Jack', 'Janet', 'Maude', 'Brandon']

(v). Generate three random first names, print them, and then add three first names at the end of your "fname" list using the "append" command.

In [7]:
#Generating three random first names and adding them to the list 'fname'.
for i in range(0,3):
    three_random_names = names.get_first_name()
    fname.append(three_random_names)
print(fname)

['Troy', 'Sandra', 'Billie', 'Ann', 'Susan', 'Jack', 'Janet', 'Maude', 'Brandon', 'Nancy', 'Daryl', 'John']

Q2. Below is a  list.

In [8]:
#my_list = ["Adam","Sam","Maddy",["Joel","Adam","Harvey","Adam"],"James","Adam",["Jordan","Nico",["Adam","Valtteri","Oscar","James"]]]
my_list = [["Adam","Sam","Joel","Joan"],["Susan","Sally","Joan","Jordan"],["Roscoe","Joan","Adam","Geoff"],["Joel","Jeremy","Sam","Gordan"]]
search_name1 = "Joan"
search_name2 = "Adam"
search_name3 = "Gordan"
print(my_list)

[['Adam', 'Sam', 'Joel', 'Joan'], ['Susan', 'Sally', 'Joan', 'Jordan'], ['Roscoe', 'Joan', 'Adam', 'Geoff'], ['Joel', 'Jeremy', 'Sam', 'Gordan']]

- [<span style="color: red;">5 points</span>] Write code to find out all the times <code>search_name1</code>,<code>search_name2</code> and <code>search_name3</code> occur in <code>my_list</code> (including nested lists). For example (assuming a 0-based index) Sam occurs twice, once in the 0th list (at the 1st place) and once in the 4th list (at the 2nd place). <br>
- [<span style="color: red;">5 points</span>]  Print the location (index) of each occurrence of the name. For Sam it would be 0,1 and 3,2 (or [0][1] and [3][2])

In [9]:
#We initialize zero to count inorder to store the sum of values in the 'for' loop
count = 0
#sub_list in the loop takes elements from my_list. sub_list is just a name, like we intialize i.
for sub_list in my_list:
    #We are checking if sub_list contains the search name or not. If yes, we proceed.
        if search_name1 in sub_list:
            #count keeps storing all sum of values for each iteration.
            count = count+1
            #Here we are using 'f-string' to embed expressions into string
            print(f"position of {search_name1}: [{my_list.index(sub_list)}] [{sub_list.index(search_name1)}]")
#We print count out of the loop, to get the total count.
print(f"count: {count}")

position of Joan: [0] [3]
position of Joan: [1] [2]
position of Joan: [2] [1]
count: 3

In [10]:
#Similarly we do this for other search names
count = 0
for sub_list in my_list:
        if search_name2 in sub_list:
            count = count+1
            print(f"position of {search_name2}: [{my_list.index(sub_list)}] [{sub_list.index(search_name2)}]")
print(f"count: {count}")

position of Adam: [0] [0]
position of Adam: [2] [2]
count: 2

In [11]:
count = 0
for sub_list in my_list:
        if search_name3 in sub_list:
            count = count+1
            print(f"position of {search_name3}: [{my_list.index(sub_list)}] [{sub_list.index(search_name3)}]")
print(f"count: {count}")

position of Gordan: [3] [3]
count: 1

In [12]:
#Alternate way for Question - 2 using functions
def search_function(name):
    count = 0
    for sub_list in my_list:
        if name in sub_list:
            count = count+1
            print(f"position of {name}: [{my_list.index(sub_list)}] [{sub_list.index(name)}]")
    print(f"count: {count}")
search_function(search_name1)
search_function(search_name2)
search_function(search_name3)
#search_function('Sam')

position of Joan: [0] [3]
position of Joan: [1] [2]
position of Joan: [2] [1]
count: 3
position of Adam: [0] [0]
position of Adam: [2] [2]
count: 2
position of Gordan: [3] [3]
count: 1

Q3. [10 points] For this step, you will use the "randint" function from the "random" module to create random integers. You can learn more about this module at https://docs.python.org/3/library/random.html. To import the "randint" function from the "random" module, please type  from random import randint in a cell, and press shift+enter.
Then
(i) Create 10 random birth-years between 1950 and 2022. Name it "byears".
(ii) Create 10 random birth-months between 1 and 12. Name it "bmonths".
(iii) Create 10 random birth-days between 1 and 31. Name it "bdays". Replace the random integer if it is not realistic, according to "bmonths" (e.g. February 29, June 31, etc, we ignore leap years in this case).
(iv) Create 10 random Credit-Scores between 100 and 800. Create a list of "CreditApproval" with "Yes" if the credit-score is higher than 650, "No" otherwise. Make sure that someone can't get a credit if they are 17 years old or younger, even if their credit-score is higher than 650. (You can find age by just subtracting their birth year from 2023)

In [13]:
import random
# Importing randint function from the random module
from random import randint

(i). 10 random birth-years between 1950 and 2022.

In [14]:
#We are printing random years using 'randint'
byears = []
for i in range(0,10):
    years = randint(1950, 2022)
    byears.append(years)
print(byears)

[1956, 1959, 1995, 1994, 1955, 2011, 2011, 2013, 1982, 1993]

(ii). 10 random birth-months between 1 and 12.

In [15]:
bmonths = []
for i in range(0,10):
    months = randint(1,12)
    bmonths.append(months)
print(bmonths)

[5, 6, 5, 6, 7, 4, 9, 5, 9, 2]

(iii). 10 random birth-days between 1 and 31.

In [16]:
bdays = []
#for months - leap year is used.
for i in range(10):
    if [1,3,5,7,8,10,12] in bmonths:
        days = randint(1,31)
    elif bmonths == 2:
        if byears % 4 == 0:
            days = randint(1,29)
        else:
            days = randint(1,28)
    else:
        days = randint(1,30)
    bdays.append(days)
print(bdays)

[12, 11, 14, 11, 29, 27, 24, 27, 16, 25]

In [17]:
#Printing birth date, month and year all together.
for i in range(10):
    print(f"{bdays[i]} - {bmonths[i]} - {byears[i]}")

12 - 5 - 1956
11 - 6 - 1959
14 - 5 - 1995
11 - 6 - 1994
29 - 7 - 1955
27 - 4 - 2011
24 - 9 - 2011
27 - 5 - 2013
16 - 9 - 1982
25 - 2 - 1993

(iv) Create 10 random Credit-Scores between 100 and 800. Create a list of "CreditApproval" with "Yes" if the credit-score is higher than 650, "No" otherwise. Make sure that someone can't get a credit if they are 17 years old or younger, even if their credit-score is higher than 650. (You can find age by just subtracting their birth year from 2023)

In [18]:
#Calculating age from birth year
age = byears
for i in range(len(age)):
    age[i] = 2023 - age[i]
print(age)

[67, 64, 28, 29, 68, 12, 12, 10, 41, 30]

In [19]:
credit_scores = []
for i in range(10):
    scores = randint(100,800)
    credit_scores.append(scores)
print(credit_scores)

Credit_approval = []
for j in range(10):
    if credit_scores[j] >= 650 and age[j] > 17:
        approval = "Yes"
    else:
        approval = "No"
    Credit_approval.append(approval)
print(Credit_approval)

[751, 504, 208, 672, 710, 523, 655, 243, 602, 218]
['Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No']

 Q4.<b>BONUS</b>: [<span style="color: red;">10 points</span>] Create a list of dictionaries called "ourdb" for these 10 people with first-name, last-name (again, you will need to use the <code>names</code> module to create random first and last names (again)), birth-year, birth-month, birth-day, CreditApproval (e.g. [{'fname': 'George', 'lname': 'Michael', 'byear': 1963, 'bmonth': 6, 'bday': 25, 'creditapproval':'yes'}, ,{...}])<br>

In [23]:
#from random import randint
current_year = 2023
Dict = {}
ourdb =  []

for i in range(10):
    fname = names.get_first_name()
    lname = names.get_last_name()

    byears = randint(1950,2022)
    bmonths =  randint(1,12)

    if bmonths == 1 or bmonths == 3 or bmonths == 5 or bmonths == 7 or bmonths == 8 or bmonths == 10 or bmonths == 12:
        bdays = randint(1,31)
    elif bmonths == 2:
        bdays = randint(1,28)
    else:
        bdays = randint(1,30)

    credit_score = randint(100,800)

    if byears < current_year:
        age = current_year - byears

    if credit_score >= 650 and age > 17:
        credit_approval = "Yes"
    else:
        credit_approval = "No"

    Dict = {
    "first-name" : fname,
    "last-name" : lname,
    "birth-year" : byears,
    "birth-month" : bmonths,
    "birth-day" : bdays,
    "age" : age,
    "credit_score": credit_score,
    "credit_approval" : credit_approval
    }

    ourdb.append(Dict)
print(ourdb)

[{'first-name': 'Julianne', 'last-name': 'Tototzintle', 'birth-year': 1952, 'birth-month': 9, 'birth-day': 17, 'age': 71, 'credit_score': 178, 'credit_approval': 'No'}, {'first-name': 'Ernestine', 'last-name': 'Bosley', 'birth-year': 1960, 'birth-month': 4, 'birth-day': 16, 'age': 63, 'credit_score': 622, 'credit_approval': 'No'}, {'first-name': 'Mary', 'last-name': 'Mitchell', 'birth-year': 1967, 'birth-month': 9, 'birth-day': 7, 'age': 56, 'credit_score': 199, 'credit_approval': 'No'}, {'first-name': 'Grace', 'last-name': 'Ayala', 'birth-year': 1985, 'birth-month': 7, 'birth-day': 20, 'age': 38, 'credit_score': 585, 'credit_approval': 'No'}, {'first-name': 'Roberto', 'last-name': 'Warne', 'birth-year': 1954, 'birth-month': 1, 'birth-day': 19, 'age': 69, 'credit_score': 213, 'credit_approval': 'No'}, {'first-name': 'Toi', 'last-name': 'Vang', 'birth-year': 1983, 'birth-month': 1, 'birth-day': 21, 'age': 40, 'credit_score': 354, 'credit_approval': 'No'}, {'first-name': 'Mary', 'last-name': 'Watson', 'birth-year': 2005, 'birth-month': 2, 'birth-day': 27, 'age': 18, 'credit_score': 274, 'credit_approval': 'No'}, {'first-name': 'Juliana', 'last-name': 'Battle', 'birth-year': 1969, 'birth-month': 11, 'birth-day': 10, 'age': 54, 'credit_score': 196, 'credit_approval': 'No'}, {'first-name': 'Wesley', 'last-name': 'Kachmarsky', 'birth-year': 1972, 'birth-month': 9, 'birth-day': 6, 'age': 51, 'credit_score': 657, 'credit_approval': 'Yes'}, {'first-name': 'Leona', 'last-name': 'Ryan', 'birth-year': 1984, 'birth-month': 10, 'birth-day': 3, 'age': 39, 'credit_score': 748, 'credit_approval': 'Yes'}]

~ Chathurya.